### ISSUE TITLE
Code Release Date

### ISSUE THREAD

**Issue by sigeek** [sharifza/schemata#1]
Good morning,
thanks for your work in scene graph generation, very well done! I would like to ask when you plan to release the code of the project.
Thanks in advance and have a nice day!
Silvia

**Comment by sharifza** [comment]
Hi Silvia! Thanks for you interest! 
We might be a bit delayed with the full pipeline (pre-processing, evaluation, etc). However, we have already cleaned up the main component (the class for the graph transformer and assimilation of schemata), and will upload it in the next few days. I will ping you here.

**Comment by sharifza** [comment]
Hi @sigeek, I uploaded the main files for this project. The rest is based on the Neural Motifs framework which we will upload after more cleanup.
