### ISSUE TITLE
where is the Prior Knowledge?

### ISSUE THREAD

**Issue by hackerchenzhuo** [sharifza/schemata#2]
Great work!
Buy the way, I don’t know wether I missed some important information in this paper, it seems that there are no details about  the Prior Knowledge (a prior knowledge base (ICP))? 

Becides, "Later we will show that our model can `accurately generate the PKG`, i.e., the commonsense that is captured from perceptions during training."
 I don’t seem to find the corresponding part.

thanks again :)

**Comment by sharifza** [comment]
Thank you @hackerchenzhuo for your interest! :) Sorry for the late response. 

The prior knowledge base is a split of triples from Visual Genome. So we take the full VG and use 90% (or 99%) of the triples as a separate knowledge base. 

Table 1, Schemata - PKG shows the results for predicting the PKG. You can find the details in bullet point 3 of the Evaluation section. 

Please let me know if this still does not answer your question so I can elaborate further.
