### ISSUE TITLE
Compare the two edge feature initialization methods

### ISSUE THREAD

**Issue by jkli-aa** [sharifza/schemata#5]
Thanks for your nice work in sgg :)
I notice that the edge feature has two initialization methods in RelModel. One is initialized by union feature and another is initialized by the spatial of subject and object. I am wondering their difference and why Schemata applies the latter method.
By the way, It seems that a learnable ScaleLayer is applied to scale the gradient of location_hlayer. Is a trick to make the training process stable? I don't know if there's anything wrong with what I understand.
Looking forward to your reply. Thanks again :)

**Comment by gyhandy** [comment]
您好，我已经收到您的来信，祝好

**Comment by sharifza** [comment]
Hi @jkli-aa. Thanks for your interest :)
In this part, we follow the code from Neural Motifs. NM used the union feature and it gave them quite a good improvement. In our case, we realized that the computational burden versus the benefit of using the union feature was not worth it (it didn't really improve the results).

The scale layer was just an inductive bias to help the network apply different weights to different features, this was motivated originally in the multimodal setting of [Depth-VRD](https://github.com/Sina-Baharlou/Depth-VRD) but in this work, it doesn't play an essential role, and you can also try your results without it.

**Comment by jkli-aa** [comment]
I got it, cheers :)

**Comment by gyhandy** [comment]
您好，我已经收到您的来信，祝好
